import type { Classification } from "../../platform-hardening/public.js";

export type AdminRoleKey = "platform_admin" | "compliance_manager" | "auditor" | "viewer";

export interface AdminRoleDefinition {
  roleKey: AdminRoleKey;
  displayName: string;
  description: string;
  defaultClearance: Classification;
  scopes: string[];
}

const platformAdminUiScopeSet = new Set([
  "access_review:read",
  "access_review:write",
  "admin_role:read",
  "admin_user:read",
  "admin_user:write",
  "ai_generation_run:read",
  "ai_generation_run:review",
  "ai_generation_run:write",
  "ai_question_version:read",
  "ai_question_version:write",
  "question_version:read",
  "question_version:write",
  "assessment:read",
  "assessment:review",
  "assessment:write",
  "assurance_alert:read",
  "audit_checkpoint:read",
  "audit_checkpoint:write",
  "audit_engagement:read",
  "audit_engagement:write",
  "audit_event:read",
  "automated_control_test:read",
  "automated_control_test:write",
  "connector:read",
  "connector:write",
  "connector_object:read",
  "connector_object:write",
  "connector_sync_run:read",
  "connector_sync_run:write",
  "consent_record:read",
  "consent_record:write",
  "custom_field_definition:read",
  "custom_field_definition:write",
  "custom_object_definition:read",
  "custom_object_definition:write",
  "custom_record:read",
  "custom_record:write",
  "custom_value:read",
  "custom_value:write",
  "data_inventory_record:read",
  "data_inventory_record:write",
  "deletion_item:read",
  "deletion_item:write",
  "deletion_job:read",
  "deletion_job:write",
  "dpia_assessment:read",
  "dpia_assessment:write",
  "evidence_link:read",
  "evidence_link:write",
  "evidence_object:read",
  "evidence_object:write",
  "evidence_version:read",
  "finding:read",
  "finding:write",
  "framework-content:read",
  "framework-content:write",
  "framework_diff:read",
  "framework_diff:write",
  "framework_update_impact:read",
  "framework_update_impact:write",
  "grc_workspace:read",
  "grc_workspace:write",
  "harmonization:read",
  "malware_scan_result:read",
  "policy_version:read",
  "policy_version:write",
  "privacy_incident:read",
  "privacy_incident:write",
  "privacy_rights_request:read",
  "privacy_rights_request:write",
  "processing_activity:read",
  "processing_activity:write",
  "remediation_task:read",
  "remediation_task:write",
  "report_export:read",
  "report_export:write",
  "retention_schedule:read",
  "retention_schedule:write",
  "risk:read",
  "risk:write",
  "risk_model:read",
  "risk_model:write",
  "trust_center_artifact:read",
  "trust_center_artifact:write",
  "universal_task:read",
  "universal_task:write",
  "vendor:read",
  "vendor:write",
  "webhook_contract:read",
  "webhook_contract:write",
  "webhook_delivery:read",
  "webhook_delivery:write"
]);

const platformAdminScopes = [
  "access_review:read",
  "access_review:write",
  "access_review_decision:read",
  "access_review_decision:write",
  "access_review_item:read",
  "access_review_item:write",
  "admin_role:read",
  "admin_user:read",
  "admin_user:write",
  "ai_generation_run:read",
  "ai_generation_run:review",
  "ai_generation_run:write",
  "ai_question_version:read",
  "ai_question_version:write",
  "question_version:read",
  "question_version:write",
  "assessment:read",
  "assessment:review",
  "assessment:write",
  "assurance_alert:read",
  "audit_checkpoint:read",
  "audit_checkpoint:write",
  "audit_engagement:read",
  "audit_engagement:write",
  "audit_event:read",
  "audit_request:read",
  "audit_request:write",
  "audit_test:read",
  "audit_test:write",
  "automated_control_test:read",
  "automated_control_test:write",
  "automated_test:read",
  "automated_test:write",
  "automated_test_run:read",
  "automated_test_run:write",
  "connector:read",
  "connector:write",
  "connector_object:read",
  "connector_object:write",
  "connector_sync_run:read",
  "connector_sync_run:write",
  "consent_event:read",
  "consent_event:write",
  "consent_purpose_version:read",
  "consent_purpose_version:write",
  "consent_record:read",
  "consent_record:write",
  "custom_field_definition:read",
  "custom_field_definition:write",
  "custom_object_definition:read",
  "custom_object_definition:write",
  "custom_record:read",
  "custom_record:write",
  "custom_value:read",
  "custom_value:write",
  "data_category:read",
  "data_category:write",
  "data_discovery_finding:read",
  "data_discovery_finding:write",
  "data_discovery_scan:read",
  "data_discovery_scan:write",
  "data_inventory_record:read",
  "data_inventory_record:write",
  "data_subject_category:read",
  "data_subject_category:write",
  "deletion_item:read",
  "deletion_item:write",
  "deletion_job:read",
  "deletion_job:write",
  "dpia:read",
  "dpia:write",
  "dpia_assessment:read",
  "dpia_assessment:write",
  "dpia_risk:read",
  "dpia_risk:write",
  "evaluation_case:read",
  "evaluation_case:write",
  "evaluation_result:read",
  "evaluation_result:write",
  "evaluation_suite:read",
  "evaluation_suite:write",
  "evidence_custody_event:read",
  "evidence_expiry_event:read",
  "evidence_expiry_event:write",
  "evidence_link:read",
  "evidence_link:write",
  "evidence_object:read",
  "evidence_object:write",
  "evidence_request:read",
  "evidence_request:write",
  "evidence_review:read",
  "evidence_review:write",
  "evidence_sample:read",
  "evidence_sample:write",
  "evidence_version:read",
  "finding:read",
  "finding:write",
  "framework-content:read",
  "framework-content:write",
  "framework_diff:read",
  "framework_diff:write",
  "framework_update_impact:read",
  "framework_update_impact:write",
  "generation_citation:read",
  "generation_citation:write",
  "grc_workspace:read",
  "grc_workspace:write",
  "harmonization:read",
  "incident_assessment:read",
  "incident_assessment:write",
  "incident_notification:read",
  "incident_notification:write",
  "knowledge_chunk:read",
  "knowledge_chunk:write",
  "lawful_basis:read",
  "lawful_basis:write",
  "legal_hold:read",
  "legal_hold:write",
  "legal_hold_item:read",
  "legal_hold_item:write",
  "malware_scan_result:read",
  "policy:read",
  "policy:write",
  "policy_attestation:read",
  "policy_attestation:write",
  "policy_control_link:read",
  "policy_control_link:write",
  "policy_version:read",
  "policy_version:write",
  "privacy_incident:read",
  "privacy_incident:write",
  "privacy_notice:read",
  "privacy_notice:write",
  "privacy_notice_version:read",
  "privacy_notice_version:write",
  "privacy_rights_request:read",
  "privacy_rights_request:write",
  "processing_activity:read",
  "processing_activity:write",
  "processing_inventory_link:read",
  "processing_inventory_link:write",
  "processing_purpose_assignment:read",
  "processing_purpose_assignment:write",
  "processing_recipient_link:read",
  "processing_recipient_link:write",
  "purpose:read",
  "purpose:write",
  "recipient:read",
  "recipient:write",
  "remediation_task:read",
  "remediation_task:write",
  "report_export:read",
  "report_export:write",
  "retention_assignment:read",
  "retention_assignment:write",
  "retention_rule:read",
  "retention_rule:write",
  "retention_schedule:read",
  "retention_schedule:write",
  "retrieval_run:read",
  "retrieval_run:write",
  "retrieved_chunk:read",
  "retrieved_chunk:write",
  "rights_request_task:read",
  "rights_request_task:write",
  "risk:read",
  "risk:write",
  "risk_model:read",
  "risk_model:write",
  "safety_check:read",
  "safety_check:write",
  "systems_asset:read",
  "systems_asset:write",
  "transfer:read",
  "transfer:write",
  "trust_center_artifact:read",
  "trust_center_artifact:write",
  "universal_task:read",
  "universal_task:write",
  "vendor:read",
  "vendor:write",
  "vendor_assessment:read",
  "vendor_assessment:write",
  "vendor_finding:read",
  "vendor_finding:write",
  "webhook_contract:read",
  "webhook_contract:write",
  "webhook_delivery:read",
  "webhook_delivery:write"
].filter((scope) => platformAdminUiScopeSet.has(scope));

export const clearanceLevels: Classification[] = ["public", "internal", "confidential", "restricted"];

export const adminRoleCatalog: AdminRoleDefinition[] = [
  {
    roleKey: "platform_admin",
    displayName: "Platform admin",
    description: "Full tenant administration across identity, evidence, assessments, and audit controls.",
    defaultClearance: "restricted",
    scopes: platformAdminScopes
  },
  {
    roleKey: "compliance_manager",
    displayName: "Compliance manager",
    description: "Runs compliance operations without identity administration privileges.",
    defaultClearance: "confidential",
    scopes: [
      "audit_event:read",
      "framework-content:read",
      "framework-content:write",
      "framework_diff:read",
      "framework_update_impact:read",
      "harmonization:read",
      "assessment:read",
      "assessment:write",
      "assessment:review",
      "evidence_object:read",
      "evidence_object:write",
      "evidence_version:read",
      "evidence_link:read",
      "evidence_link:write",
      "finding:read",
      "finding:write",
      "remediation_task:read",
      "remediation_task:write",
      "risk:read",
      "risk:write",
      "risk_model:read",
      "report_export:read",
      "report_export:write",
      "universal_task:read",
      "universal_task:write",
      "ai_generation_run:read",
      "ai_generation_run:review",
      "ai_generation_run:write",
      "ai_question_version:read",
      "ai_question_version:write",
      "question_version:read",
      "connector:read",
      "retention_schedule:read",
      "retention_schedule:write",
      "custom_object_definition:read",
      "custom_object_definition:write"
    ]
  },
  {
    roleKey: "auditor",
    displayName: "Auditor",
    description: "Read-focused access for evidence, audit trail, assessments, and reporting.",
    defaultClearance: "confidential",
    scopes: [
      "audit_event:read",
      "audit_checkpoint:read",
      "framework-content:read",
      "framework_diff:read",
      "framework_update_impact:read",
      "harmonization:read",
      "assessment:read",
      "assessment:review",
      "evidence_object:read",
      "evidence_version:read",
      "evidence_link:read",
      "finding:read",
      "remediation_task:read",
      "risk:read",
      "risk_model:read",
      "report_export:read",
      "universal_task:read",
      "question_version:read",
      "ai_generation_run:read",
      "ai_question_version:read",
      "connector:read",
      "data_inventory_record:read",
      "processing_activity:read",
      "dpia_assessment:read",
      "privacy_rights_request:read",
      "consent_record:read",
      "privacy_incident:read",
      "retention_schedule:read",
      "custom_object_definition:read"
    ]
  },
  {
    roleKey: "viewer",
    displayName: "Viewer",
    description: "Limited read-only access to low-risk operational views.",
    defaultClearance: "internal",
    scopes: [
      "audit_event:read",
      "framework-content:read",
      "harmonization:read",
      "assessment:read",
      "evidence_object:read",
      "universal_task:read",
      "question_version:read",
      "report_export:read",
      "policy_version:read",
      "access_review:read",
      "vendor:read",
      "audit_engagement:read",
      "trust_center_artifact:read",
      "grc_workspace:read",
      "custom_object_definition:read"
    ]
  }
];

export function findAdminRole(roleKey: string): AdminRoleDefinition | undefined {
  return adminRoleCatalog.find((role) => role.roleKey === roleKey);
}

export function scopesForRoleKeys(roleKeys: string[]): string[] {
  const scopes = new Set<string>();
  for (const roleKey of roleKeys) {
    const role = findAdminRole(roleKey);
    for (const scope of role?.scopes ?? []) {
      scopes.add(scope);
    }
  }
  return [...scopes].sort();
}
