export const IDENTITY_TENANT_REPOSITORY = Symbol("IDENTITY_TENANT_REPOSITORY");
export const ADMIN_USERS_REPOSITORY = Symbol("ADMIN_USERS_REPOSITORY");
export const PLATFORM_ONBOARDING_REPOSITORY = Symbol("PLATFORM_ONBOARDING_REPOSITORY");
